In [19]:
import pandas as pd
import gc

Прочитайте fines.csv файл, который вы сохранили в предыдущем упражнении.

In [20]:
df = pd.read_csv('../ex04/fines.csv', sep =',')
df.head()

      CarNumber  Refund   Fines    Make  Model  Year
0  Y163O8161RUS     2.0  3200.0    Ford  Focus  1989
1   E432XX77RUS     1.0  6500.0  Toyota  Camry  1995
2   7184TT36RUS     1.0  2100.0    Ford  Focus  1984
3  X582HE161RUS     2.0  2000.0    Ford  Focus  2015
4  92918M178RUS     1.0  5700.0    Ford  Focus  2014

In [21]:
df[df['Refund'] == 0]

     CarNumber  Refund   Fines    Make  Model  Year
926  NEWCAR002     0.0  2500.0  Toyota  Prius  2015
929  NEWCAR005     0.0  4300.0    Audi     A4  2012

In [22]:
df.loc[df['Refund'] == 0, 'Refund'] = None

Итерации: во всех следующих подзадачах необходимо выполнить вычисления fines/refund*year для каждой строки. Создайте новый столбец с вычисленными данными. Измерьте время с помощью магической команды %%timeit в ячейке.
- Напишите функцию, которая циклически проходит по фрейму данных for i in range(0, len(df)), используя iloc, и , append()к списку. Присвойте результат функции новому столбцу фрейма данных.
- Сделайте это с помощью iterrows().
- Сделайте это с помощью apply() лямбда-функции.
- Сделайте это, используя Series объекты из фрейма данных.
- Сделайте то же, что и в предыдущей подзадаче, но используйте метод .values.

In [23]:
%%timeit

result = []
for i in range(0, len(df)):
    calc = df['Fines'].iloc[i] / df['Refund'].iloc[i] * df['Year'].iloc[i]
    result.append(calc)

df['calc_for'] = result

39.3 ms ± 902 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [24]:
%%timeit

results = []
for idx, row in df.iterrows():
    results.append(row["Fines"] / row["Refund"] * row["Year"])
df["calc_iterrows"] = results

86.8 ms ± 2.75 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [25]:
%%timeit

df['calc_apply'] = df.apply(lambda x: x['Fines'] / x['Refund'] * x['Year'], axis = 1)

19 ms ± 535 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [26]:
%%timeit

df['calc_series'] = df['Fines'] / df['Refund'] * df['Year']

455 μs ± 24.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [27]:
%%timeit
df["calc_values"] = df["Fines"].values / df["Refund"].values * df["Year"].values

206 μs ± 12.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [28]:
df.head()

,CarNumber,Refund,Fines,Make,Model,Year,calc_for,calc_iterrows,calc_apply,calc_series,calc_values
0,Y163O8161RUS,2.0,3200.0,Ford,Focus,1989,3182400.0,3182400.0,3182400.0,3182400.0,3182400.0
1,E432XX77RUS,1.0,6500.0,Toyota,Camry,1995,12967500.0,12967500.0,12967500.0,12967500.0,12967500.0
2,7184TT36RUS,1.0,2100.0,Ford,Focus,1984,4166400.0,4166400.0,4166400.0,4166400.0,4166400.0
3,X582HE161RUS,2.0,2000.0,Ford,Focus,2015,2015000.0,2015000.0,2015000.0,2015000.0,2015000.0
4,92918M178RUS,1.0,5700.0,Ford,Focus,2014,11479800.0,11479800.0,11479800.0,11479800.0,11479800.0

Индексирование: измерьте время с помощью волшебной команды %%timeit в ячейке.
- Получите строку для определенного CarNumber, например, «O136HO197RUS».
- Установите индекс в вашем фрейме данных с помощью CarNumber.
- И снова получите ряд за то же самое CarNumber.

In [29]:
%%timeit

row = df[df['CarNumber'] == 'O136HO197RUS']

651 μs ± 36.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [34]:
%%timeit

df_index = df.set_index('CarNumber')

788 μs ± 37.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [39]:
%%timeit

row_idx = df_index.loc['O136HO197RUS']

283 μs ± 17.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [38]:
row_idx

,Refund,Fines,Make,Model,Year,calc_for,calc_iterrows,calc_apply,calc_series,calc_values
CarNumber,,,,,,,,,,
O136HO197RUS,2.0,7800.0,Toyota,Corolla,1999,7796100.0,7796100.0,7796100.0,7796100.0,7796100.0
O136HO197RUS,2.0,7800.0,Toyota,Corolla,1991,7764900.0,7764900.0,7764900.0,7764900.0,7764900.0

Понижающее приведение:
- Запустите df.info(memory_usage='deep') и обратите внимание на Dtype и использование памяти.
- Преобразуйте copy() свой исходный фрейм данных в другой фрейм данных, optimized_df.
- Понижающее приведение от float64 к float32 для всех столбцов.
- Понижение от int64 до наименьшего возможного числового типа D.
- Запустите info(memory_usage='deep') новый фрейм данных. Обратите внимание на Dtype и использование памяти.

In [40]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CarNumber      930 non-null    object
 1   Refund         928 non-null    float64
 2   Fines          930 non-null    float64
 3   Make           930 non-null    object
 4   Model          919 non-null    object
 5   Year           930 non-null    int64
 6   calc_for       928 non-null    float64
 7   calc_iterrows  928 non-null    float64
 8   calc_apply     928 non-null    float64
 9   calc_series    928 non-null    float64
 10  calc_values    928 non-null    float64
dtypes: float64(7), int64(1), object(3)
memory usage: 232.9 KB

In [47]:
optimized_df = df.copy()

In [48]:
for col in optimized_df.select_dtypes(include="float64"):
    optimized_df[col] = optimized_df[col].astype("float32")

In [49]:
for col in optimized_df.select_dtypes(include="int64"):
    optimized_df[col] = optimized_df[col].astype("int16")

In [50]:
optimized_df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CarNumber      930 non-null    object
 1   Refund         928 non-null    float32
 2   Fines          930 non-null    float32
 3   Make           930 non-null    object
 4   Model          919 non-null    object
 5   Year           930 non-null    int16
 6   calc_for       928 non-null    float32
 7   calc_iterrows  928 non-null    float32
 8   calc_apply     928 non-null    float32
 9   calc_series    928 non-null    float32
 10  calc_values    928 non-null    float32
dtypes: float32(7), int16(1), object(3)
memory usage: 202.0 KB

Категории:
- Измените object тип столбцов на category.
- На этот раз проверьте использование памяти. Вероятно, оно уменьшится в 2–3 раза по сравнению с исходным фреймом данных.

In [51]:
for col in optimized_df.select_dtypes('object'):
    optimized_df[col] = optimized_df[col].astype('category')

In [52]:
optimized_df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CarNumber      930 non-null    category
 1   Refund         928 non-null    float32
 2   Fines          930 non-null    float32
 3   Make           930 non-null    category
 4   Model          919 non-null    category
 5   Year           930 non-null    int16
 6   calc_for       928 non-null    float32
 7   calc_iterrows  928 non-null    float32
 8   calc_apply     928 non-null    float32
 9   calc_series    928 non-null    float32
 10  calc_values    928 non-null    float32
dtypes: category(3), float32(7), int16(1)
memory usage: 85.4 KB

Очистка памяти:
- Используя библиотеку gc и команду %reset_selective, очистите только память вашего исходного фрейма данных.

In [53]:
%reset_selective -f df

gc.collect()

1089